### ISSUE TITLE
[cloud-spring-cloud-gcp-secret-manager]:

### ISSUE THREAD

**Issue by ivanzhujunwei** [googlecodelabs/feedback#1220] opened 2023-04-25 13:47 UTC
https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-secret-manager#4
I tried both ways (@Value("${sm://greeting}") OR defined in application.properties file), but still got the secret value as null. 
I am using spring boot 3.0.6-SNAPSHOT with the following:
`<dependency>
	<groupId>com.google.cloud</groupId>
	<artifactId>spring-cloud-gcp-starter-secretmanager</artifactId>
</dependency>`

**Comment by ivanzhujunwei** [comment] 2023-04-27 01:17
Someone [mentioned this](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1762#issuecomment-1523993756) which is different [from the doc](https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-secret-manager#4), will spend some time to try it out.

**Comment by meteatamel** [comment] 2023-06-02 06:31
Hi @glasnt, I think you updated this codelab recently. Did you run into this issue? If not, I think we can close this?

**Comment by glasnt** [comment] 2023-06-04 23:09
Step 3 in the codelab gets you to use Spring Boot 2.7.10 through the `curl https://start.spring.io/starter.tgz` command. 

After adding `spring-cloud-gcp-starter-secretmanager` and running `mvn dependencies:tree`, you can see it's using `com.google.cloud:spring-cloud-gcp-starter-secretmanager:jar:3.5.1:compile`. 

If you start with Spring Boot 3.0.6-SNAPSHOT instead, then add the secret manager dependency and check the tree again, you get `com.google.cloud:spring-cloud-gcp-starter-secretmanager:jar:4.3.1:compile`

This is a major version difference in the Secret Manager package, so there's probably breaking changes. 

Checking the docs, I found [Migration Guide from Spring Cloud GCP 3.x to 4.x](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/asciidoc/migration-guide-3.x.adoc#secret-manager) which says: 

> Spring Cloud GCP 4.0 is built on Spring Boot 3.0
> ...
> [Secret Manager](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/asciidoc/migration-guide-3.x.adoc#secret-manager): 
> To enable the application to fetch a secret from SecretManager, add `spring.config.import=sm://` in the `application.properties`

I was able to reproduce a broken error as above, and was able to resolve it by adding `spring.config.import=sm://` to `application.properties`. 

Since the codelab still uses Spring Boot 2.7.x, it will use Spring Cloud GCP 3.x, so no additional change is required. 

When this codelab is updated, this will need to be added.

**Closed as completed by glasnt** 2023-06-04 23:09 UTC
