### ISSUE TITLE
[cloud-text-speech-python3]: AttributeError: 'coroutine' object has no attribute 'audio_content'

### ISSUE THREAD

**Issue by jcmachicao** [googlecodelabs/feedback#868] opened 2021-01-02 14:41 UTC
AttributeError: 'coroutine' object has no attribute 'audio_content'

**Comment by PicardParis** [comment] 2021-01-05 08:01
Hi @jcmachicao,
I went through the codelab and couldn't reproduce your issue (I do get proper WaveNet speech, as expected).
Do you have more details?
Is there any error when you call `client.synthesize_speech`?

**Comment by PicardParis** [comment] 2021-01-27 09:34
Closing this ticket. Please reopen if you have more details...

**Closed as completed by PicardParis** 2021-01-27 09:34 UTC
