### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by Vivek-Dh** [googlecodelabs/feedback#523] opened 2018-12-03 08:29 UTC
This mentioned step : $ ./mvnw -DskipTests com.google.cloud.tools:jib-maven-plugin:build \
  -Dimage=gcr.io/$GOOGLE_CLOUD_PROJECT/hello-java:v1 keeps on giving the below error -- 

 **[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.10.0:build (default-cli) on project demo: Build image failed, perhaps you should set a credential helper name with the configuration '<to><credHelper>' or set credentials for 'gcr.io' in your Maven settings: Unauthorized for gcr.io/spring-boot-cloud-shell/hello-java: 401 Unauthorized
[ERROR] {"errors":[{"code":"UNAUTHORIZED","message":"You don't have the needed permissions to perform this operation, and you may have invalid credentials.**

I have tried running "gcloud auth configure-docker" and also intalling docker-credential-gcr but it still results in the same error.

**Comment by saturnism** [comment] 2019-10-02 14:18
duplicate of https://github.com/googlecodelabs/feedback/issues/620

i think it's the same API enablement issue :)

**Closed as completed by saturnism** 2019-10-02 14:18 UTC
Labels: duplicate
