### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by bogdan-marian** [googlecodelabs/feedback#1140] opened 2022-08-16 06:44 UTC
When will we get the same type of tutorials but with gradle? At the moment there is no good way to build a standard grade java app. I mean you can get it to work but you need to guess and match. Some files you have to use yaml and some files xml and you need to find by try and error what files to use.

**Comment by meteatamel** [comment] 2023-04-20 09:37
Duplicate of [1218](https://github.com/googlecodelabs/feedback/issues/1218)

**Closed as not planned by meteatamel** 2023-04-20 09:37 UTC
