### ISSUE TITLE
[cloud-speech-text-python3]…

### ISSUE THREAD

**Issue by resul-ai** [googlecodelabs/feedback#1247] opened 2023-06-27 09:44 UTC
`print_response(response)` should be ` print_result(response)`

**Comment by PicardParis** [comment] 2023-06-27 09:55
Hi,
I believe this works as it should (`print_response` calls `print_result` in a loop).
Do you get an error message?

**Comment by PicardParis** [comment] 2023-06-28 08:55
Hi
- I couldn't reproduce/guess a potential problem.
- I'm closing the issue for now. Please reopen it if you see an error.

**Closed as completed by PicardParis** 2023-06-28 08:55 UTC
Labels: cloud, python, ml
