### ISSUE TITLE
[cloud-natural-language-python3] …

### ISSUE THREAD

**Issue by metandres** [googlecodelabs/feedback#1135] opened 2022-08-04 07:58 UTC
AttributeError: module 'google.cloud.language' has no attribute 'Document'

**Comment by PicardParis** [comment] 2022-08-04 10:07
Hi @metandres 
- I retested the codelab and couldn't reproduce your error.
- Things I'd recheck:
  - Make sure the client library is properly installed:
    - `pip3 install --upgrade google-cloud-language`
    - `pip3 freeze | grep google-cloud-language`
    - This gives: `google-cloud-language==2.5.1`
  - `Document` is part of the module:
    ```
    from google.cloud import language
    print(dir(language))

    ['AnalyzeEntitiesRequest',... , 'Document', ...]
    ```
- I'm closing the ticket for now. If needed, feel free to reopen it with details about your environment.

**Closed as completed by PicardParis** 2022-08-04 10:07 UTC
Labels: cloud, python, ml
