### ISSUE TITLE
[cloud-natural-language-python3]: "no attribute Document" error

### ISSUE THREAD

**Issue by eamonious** [googlecodelabs/feedback#1094] opened 2022-03-23 17:32 UTC
This code doesn't run in a Google Colab Notebook running python.

It throws an error saying that language has no attribute Document, which appears to be correct.

**Comment by eamonious** [comment] 2022-03-23 17:33
https://codelabs.developers.google.com/codelabs/cloud-natural-language-python3#8

**Comment by PicardParis** [comment] 2022-03-24 07:09
Thanks for the feedback. I should be able to have a look today.

**Comment by PicardParis** [comment] 2022-03-24 10:39
- What I did
  - Tested the codelab from an IPython session under Cloud Shell
  - Everything still works as expected
  - Updated the codelab (no code change) with the current library/Python/IPython versions:
    - `google-cloud-language==2.0.0` ->`google-cloud-language==2.4.1`
    - `Python 3.7.3` -> `Python 3.9.2`
    - `IPython 7.19.0` -> `IPython 8.1.1`
- I'm not able to reproduce your issue.
  - At which step do you have the error? Is the client library installed?
  - Can you provide more details or share the notebook?

**Comment by eamonious** [comment] 2022-03-24 17:50
Here is the notebook link:
https://colab.research.google.com/drive/1UF15Cu9rICdmsUQrcnkBqDxjNyZ5oCdl?usp=sharing

Thanks for helping.

**Comment by PicardParis** [comment] 2022-03-28 08:15
I cannot access the notebook (sent you a sharing request).

**Comment by PicardParis** [comment] 2022-09-23 09:29
- The error cause was probably that the notebook runtime had an older version `1.x.x` of the library
- You can update it with the following command: `!pip install --upgrade google-cloud-language` (current version is `2.5.2`)
- You can also use a Python virtual environment
- I'm closing the ticket but feel free to reopen it with additional details

**Comment by eamonious** [comment] 2022-10-11 07:09
Open a new notebook on Google Colab.  (The google language packages are
pre-installed.)   Try to run the code exactly as presented on the Codelabs
tutorial at the page that I linked.   The error will throw when you
actually try to run the function.

**Comment by PicardParis** [comment] 2022-10-24 08:19
Hi,
- I did a quick test last week:
  - The default Colab runtime does indeed have the client library preinstalled, but it's an old version (`google-cloud-language-1.2.0`)
  - This explains your error message (package structures changed between `1.x` and `2.x`)
  - If you run `! pip install --upgrade google-cloud-language`, it will install the latest version (currently `google-cloud-language-2.6.1`)
  - Note that you need to restart the runtime to use the new version (you do get a warning at the end of the installation)
  - Then, without any prior setup, you'll meet authentication issues (you must define a Google Cloud project and authenticate within the Colab environment)
- I'll try to transpose the tutorial (designed to be used in Cloud Shell) to authenticate in a Colab notebook, when I have some bandwidth (hopefully later this week, but no promise)
- Reopening this issue...

**Comment by PicardParis** [comment] 2022-10-25 13:59
Hi,
- I made a quick port to Colab:
  - [Run in Colab](https://colab.research.google.com/github/PicardParis/cloud-snippets/blob/main/python/colab/Using%20the%20Natural%20Language%20API%20with%20Python.ipynb)
  - I only copied the Python code (for details, keep referring to the original [tutorial](https://codelabs.developers.google.com/codelabs/cloud-natural-language-python3))
- Please let me know how that goes

**Comment by PicardParis** [comment] 2022-10-28 17:32
Please reopen this issue in case of problem...

**Closed as completed by PicardParis** 2022-10-28 17:32 UTC
Labels: cloud, python, ml
