### ISSUE TITLE
[cloud-app-engine-python]:

### ISSUE THREAD

**Issue by anthraxmonki** [googlecodelabs/feedback#503] opened 2018-10-23 00:57 UTC
Opening a new cloud console session just loads the running server/app engine app, or, when it does bring us to a clean shell, which seems random... none of the shells take any input/all the new + shells are frozen.

Safari Version 12.0 (13606.2.11)

**Comment by PicardParis** [comment] 2019-12-20 10:58
Thank you for the feedback. I couldn't reproduce the issue. Closing it...
_(feel free to reopen if you have more details)_

**Closed as completed by PicardParis** 2019-12-20 10:58 UTC
