### ISSUE TITLE
[cloud-kubernetes-aspnetcore]:

### ISSUE THREAD

**Issue by kjegru** [googlecodelabs/feedback#294] opened 2017-10-25 11:31 UTC
> -bash: deployment: command not found

The new version came up without needing to run the command.

**Comment by meteatamel** [comment] 2019-05-20 05:32
Not sure what the issue is here?

**Comment by meteatamel** [comment] 2019-07-10 11:04
Closing. Please re-open if you still see the issue.

**Closed as completed by meteatamel** 2019-07-10 11:04 UTC
